version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: groom-redis
    ports:
      - "6379:6379"
    networks:
      - groom-network

  app:
    image: groom-server:test
    container_name: groom-server
    ports:
      - "8080:8080"
    networks:
      - groom-network
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=test

networks:
  groom-network:
