spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:groom}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  jwt:
    access-token:
      secret: dev-jwt-access-token-secret-key
      expiration: 7200000
    refresh-token:
      secret: dev-jwt-refresh-token-secret-key
      expiration: 2592000000
email:
  host: ${EMAIL_HOST}
  port: 587
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  authentication:
    object:
      ttl: ${EMAIL_AUTHENTICATION_OBJECT_TTL:300}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true