spring:
  application:
    name: Groom-Server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
  cache:
    expiry-time: ${CACHE_EXPIRY_TIME:120}
    maximum-size: ${CACHE_MAXIMUM_SIZE:1000}
    type: caffeine
server:
  port: ${SERVER_PORT:8080}