spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6379
email:
    host: smtp.example.com
    port: 587
    username: test-email@example.com
    password: test-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true